;; 1. (print(EQL (CAR(CDADR '((SIDOROV GOOD) (IVANOV EXCELLENT) (PETROV SATISF)))) 'EXCELLENT))

;; 2. (print(EQL (CDDAR'((DB IVANOV SATISF) (DB PETROV EXCELLENT))) 'EXCELLENT))

;; 3. (print(EQL (CADR'((IVANOV PETROV) (EXCELLENT SATISF))) 'EXCELLENT))
